name: Semantic Search on Movie Plots

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Sets up a Python environment for you to use
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installs your project's dependencies from requirements.txt
      - name: Install dependencies
        working-directory: ./Movie-Search-Assignment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs your tests using the unittest discover command
      - name: Run tests with unittest
        run: python -m unittest discover -v